import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

import { SpinBox, Button, CheckBox, Slider, LineEdit, ScrollView, ListView,
    HorizontalBox, VerticalBox, GridBox, StandardButton, Palette } from "std-widgets.slint";

@rust-attr(derive(serde::Serialize, serde::Deserialize))
export struct TodoItem  {
    title: string,
    checked: bool,
    dir: bool,
}


export component AppWindow inherits Window {
    in-out property <string> path: "/home/jord/coding/texturizers";
    callback glob-path();

    in-out property <[TodoItem]> todo-model: [];

    VerticalBox {
        le := LineEdit {
            text: root.path;

            init() => {
                self.focus()
            }
            edited(new) => {
                root.path = new;
                root.glob-path();
            }
        }

        ListView {
            for todo in root.todo-model: HorizontalLayout {
                width: 300px;
                CheckBox {
                    toggled => {
                        todo.checked = self.checked;
                    }

                    text: todo.title;
                    checked: todo.checked;
                }

                if todo.dir:  
                    Button {
                    text: "-->";
                    checked: todo.checked;

                    clicked() => {
                        root.path = "\{root.path}" + "\{todo.title}";
                        le.text = root.path;
                        root.glob-path();
                    }
                }
            }
        }
    }
}
