import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

import { SpinBox, Button, CheckBox, Slider, LineEdit, ScrollView, ListView,
    HorizontalBox, VerticalBox, GridBox, StandardButton, Palette } from "std-widgets.slint";

@rust-attr(derive(serde::Serialize, serde::Deserialize))
export struct TodoItem  {
    title: string,
    checked: bool,
}

export component AppWindow inherits Window {
    in-out property <string> path: "";
    callback glob-path();

    in-out property <[TodoItem]> todo-model: [];

    VerticalBox {
        le := LineEdit {
            text: {
                root.path
            };

            edited(new) => {
                root.path = new;
                root.glob-path();
            }
        }

        ListView {
            for todo in root.todo-model: HorizontalLayout {
                CheckBox {
                    toggled => {
                        todo.checked = self.checked;
                    }

                    text: todo.title;
                    checked: todo.checked;
                }
            }
        }
    }
}
